version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: online-games-store

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
