version: '3.9'

services:

  app:
    container_name: "JavaAPI"
    build: .
    image: online-games-store
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/online-games-store
      spring.rabbitmq.host: rabbitmq
      spring.redis.host: redis
    ports:
      - "8080:8080"
    networks:
      - api-network
    depends_on:
      - db

  db:
    container_name: "PostgreSQL"
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: online-games-store
    networks:
      - api-network

  adminer:
    container_name: "Adminer"
    image: adminer
    ports:
      - "8090:8080"
    networks:
      - api-network

  redis:
    container_name: "Redis"
    image: redis
    networks:
      - api-network

  rabbitmq:
    container_name: "RabbitMQ"
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
