spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
    timeout:
  redis:
    host: localhost
    password: password
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online-games-store
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  sql:
    init:
      mode: always
      platform: postgre